import { BiWifi, BiBluetooth } from 'react-icons/bi'
import { v4 as uuid } from "uuid"


export const products = [
    {
        "type": "Rug",
        "title": "ASUS TUF GAMING P3",
        "brand": "Asus",
        "price": 2400,
        "size": "СРЕДНИЙ",
        "color": "СЕРЫЙ",
        "backlight": false,
        "coating": "Speed + Control",
        "material": "ТКАНЬ",
        "baseMaterial": "РЕЗИНА",
        "dimensions": null,
        "wireless charger": null,
        "additionalInformation": null,
        "description": "TUF Gaming P3 – это прочный коврик для мыши с гладкой тканевой поверхностью, обеспечивающей высокую точность позиционирования. Он оформлен в стиле серии TUF Gaming, обладает простроченными краями и резиновой основой и прекрасно подходит для игр любых жанров. Идеально гладкая тканевая поверхность коврика TUF Gaming P3 прекрасно подходит для игр. Мышь скользит по нему без малейших усилий, позволяя достичь высокой скорости и точности позиционирования, которые так необходимы для победы.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/ASUS%20TUF%20Gaming%20P3_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "ASUS ROG Sheath PINK",
        "brand": "Asus",
        "price": 4400,
        "size": "ОГРОМНЫЙ",
        "color": "ГОЛУБОЙ",
        "backlight": false,
        "coating": null,
        "material": "ТКАНЬ",
        "baseMaterial": "РЕЗИНА",
        "dimensions": "900Х440 ММ",
        "wireless charger": false,
        "additionalInformation": null,
        "description": "Мягкий тканевый коврик для мыши с большой и гладкой поверхностью, противоскользящим основанием и простроченными краями",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/ASUS%20ROG%20Sheath%20PINK_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "ASUS ROG BALTEUS",
        "brand": "Asus",
        "price": 12400,
        "size": "СРЕДНИЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": true,
        "coating": null,
        "material": null,
        "baseMaterial": "РЕЗИНА",
        "dimensions": "370Х320 ММ",
        "wireless charger": false,
        "additionalInformation": "USB - РАЗЪЕМ ДЛЯ ПОДКЛЮЧЕНИЯ ДОПОЛНИТЕЛЬНЫХ УСТРОЙСТВ",
        "description": "Коврик ASUS ROG Balteus применяется для обеспечения точности работы компьютерной мыши в процессе игры. Предмет выполнен в сером цвете с рисунком логотипа. Материал изготовления – резина, что обеспечивает отсутствие скольжения коврика при движении руки. ASUS ROG Balteus не оснащен подставкой под запястье, беспроводной зарядкой, обладает подсветкой. Размер – средний, параметры составляют 370x320x7.9 мм. Дополнительными опциями являются USB-разъем для подключения дополнительных устройств, 15-зонная подсветка Aura.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/ASUS%20ROG%20Balteus%20(1).png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "ASUS NH01 ROG BALTEUS QI",
        "brand": "Asus",
        "price": 12400,
        "size": "СРЕДНИЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": true,
        "coating": null,
        "material": null,
        "baseMaterial": "РЕЗИНА",
        "dimensions": "370Х320 ММ",
        "wireless charger": false,
        "additionalInformation": "USB - РАЗЪЕМ ДЛЯ ПОДКЛЮЧЕНИЯ ДОПОЛНИТЕЛЬНЫХ УСТРОЙСТВ",
        "description": "Коврик ASUS ROG Balteus применяется для обеспечения точности работы компьютерной мыши в процессе игры. Предмет выполнен в сером цвете с рисунком логотипа. Материал изготовления – резина, что обеспечивает отсутствие скольжения коврика при движении руки. ASUS ROG Balteus не оснащен подставкой под запястье, беспроводной зарядкой, обладает подсветкой. Размер – средний, параметры составляют 370x320x7.9 мм. Дополнительными опциями являются USB-разъем для подключения дополнительных устройств, 15-зонная подсветка Aura.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Asus%20NH01%20ROG%20BALTEUS%20QI.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "BLIZZARD OVERWATCH CHARACTER ICON",
        "brand": "Blizzard",
        "price": 2900,
        "size": "СРЕДНИЙ",
        "color": "РАЗНОЦВЕТНЫЙ",
        "backlight": false,
        "coating": null,
        "material": "ПОЛИЭСТЕР",
        "baseMaterial": "КАУЧУК",
        "dimensions": "350Х240 ММ",
        "wirelesscharger": false,
        "additionalInformation": null,
        "description": "Коврик для мыши Character Icon даст вашим быстрым щелчкам и разрушительным ударам в голову красочную основу. Оживите свое игровое пространство, добавив его в свою коллекцию Overwatch. Ковёр Overwatch Character Icon специально разработан для фанатов игры Overwatch. Покрытие коврика выполнено из плотной ткани, которая усиливает чувствительность взаимодействия игровой мыши с поверхностью. Резиновое основание не даёт коврику скользить по столу, когда вы активно двигаете рукой. Износостойкие края с гладкой прострочкой предотвращают преждевременный износ при ежедневном использовании. С целью уменьшения частоты стирки производитель рекомендует через день протирать изделие влажными салфетками.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Blizzard%20Overwatch%20Character%20Icon_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "CORSAIR MM200 CLOTH GAMING MOUSE MAT - MEDIUM",
        "brand": "Crosair",
        "price": 1900,
        "size": "СРЕДНИЙ",
        "color": "ОСНОВНОЙ ЦВЕТ",
        "backlight": false,
        "coating": "SPEED",
        "material": "ТКАНЬ",
        "baseMaterial": "РЕЗИНА",
        "dimensions": null,
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Коврик Corsair MM200 Cloth Gaming Mouse Mat - Medium – это надежный аксессуар, разработанный специально для того, чтобы вы могли получить абсолютный комфорт в процессе игры. Модель с покрытием speed гарантирует плавное и точное скольжение мыши. Изготовлен коврик из высококачественной ткани, которая гарантирует долговечность и износостойкость даже при ежедневной интенсивной эксплуатации. Резиновая основа Corsair MM200 Cloth Gaming Mouse Mat - Medium обеспечивает прекрасное сцепление с поверхностью, поэтому коврик не скользит даже в процессе интенсивных манипуляций. Коврик обладает средними размерами 360X300X2 мм, что позволяет вам получить достаточно большую область для управления мышью. Аксессуар предусматривает небольшой вес, что наряду с удобной упаковкой способствует комфортной транспортировке. Ярким акцентом на черном полотне является желтая полоса, которую разделяет логотип.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Corsair%20MM200%20Cloth%20Gaming%20Mouse%20Mat%20-%20Medium_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "CORSAIR MM200 CLOTH GAMING MOUSE MAT - EXTENDED",
        "brand": "Crosair",
        "price": 3800,
        "size": "ОГРОМНЫЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": false,
        "coating": "SPEED",
        "material": "ТКАНЬ",
        "baseMaterial": "РЕЗИНА",
        "dimensions": null,
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Коврик Corsair MM200 Cloth Gaming Mouse Mat - Medium – это надежный аксессуар, разработанный специально для того, чтобы вы могли получить абсолютный комфорт в процессе игры. Модель с покрытием speed гарантирует плавное и точное скольжение мыши. Изготовлен коврик из высококачественной ткани, которая гарантирует долговечность и износостойкость даже при ежедневной интенсивной эксплуатации. Резиновая основа Corsair MM200 Cloth Gaming Mouse Mat - Medium обеспечивает прекрасное сцепление с поверхностью, поэтому коврик не скользит даже в процессе интенсивных манипуляций. Коврик обладает средними размерами 360X300X2 мм, что позволяет вам получить достаточно большую область для управления мышью. Аксессуар предусматривает небольшой вес, что наряду с удобной упаковкой способствует комфортной транспортировке. Ярким акцентом на черном полотне является желтая полоса, которую разделяет логотип.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Corsair%20MM200%20Cloth%20Gaming%20Mouse%20Mat%20-%20Extended_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "HYPERX FURY S PRO M",
        "brand": "HyperX",
        "price": 1700,
        "size": "СРЕДНИЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": false,
        "coating": "SPEED + Control",
        "material": "ТКАНЬ",
        "baseMaterial": "РЕЗИНА",
        "dimensions": null,
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Коврик HyperX Fury S Pro M можно рекомендовать любому профессиональному геймеру, для которого особенно важен комфорт управления мышью в жестоких онлайн-сражениях. Он имеет габариты 360 х 300 мм и предлагает игроку большое пространство для движения мыши по специальной тканевой поверхности, оптимальной для мышей с оптическим сенсором. Сверху коврик имеет гладкую поверхность, способствующую свободному скольжению манипулятора, а снизу он снабжен резиновым основанием, которое не позволяет ему двигаться по компьютерному столу. Украшенный логотипом производителя среднего размера черный коврик для мыши HyperX Fury S Pro M можно свернуть в трубочку для большего удобства перевозки в сумке или рюкзаке. Подарив геймеру полный контроль над перемещениями мыши, он станет по-настоящему востребованным и удобным аксессуаром, верным спутником своего владельца. Качественно изготовленный коврик с простроченным краем выдержит долгую и активную эксплуатацию.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/HyperX%20Fury%20S%20Pro%20M_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "HYPERX FURY S PRO XL",
        "brand": "HyperX",
        "price": 3900,
        "size": "ОГРОМНЫЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": false,
        "coating": "SPEED + Control",
        "material": "ТКАНЬ",
        "baseMaterial": "РЕЗИНА",
        "dimensions": "900Х420 ММ",
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Коврик HyperX Fury S Pro M можно рекомендовать любому профессиональному геймеру, для которого особенно важен комфорт управ-ления мышью в жестоких онлайн-сражениях. Он имеет габариты 360 х 300 мм и предлагает игроку большое пространство для движения мыши по специальной тканевой поверхности, оптимальной для мышей с оптическим сенсором. Сверху коврик имеет гладкую поверхность, способствующую свободному скольжению манипулятора, а снизу он снабжен резиновым основанием, которое не позволяет ему двигаться по компьютерному столу. Украшенный логотипом производителя среднего размера черный коврик для мыши HyperX Fury S Pro M можно свернуть в трубочку для большего удобства перевозки в сумке или рюкзаке. Подарив геймеру полный контроль над перемещениями мыши, он станет по-настоящему востребованным и удобным аксессуаром, верным спутником своего владельца. Качественно изготовленный коврик с простроченным краем выдержит долгую и активную эксплуатацию.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/HyperX%20Fury%20S%20Pro%20XL_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "HYPERX FURY ULTRA RGB M",
        "brand": "HyperX",
        "price": 8100,
        "size": "СРЕДНИЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": true,
        "coating": "SPEED + Control",
        "material": "ПЛАСТИК",
        "baseMaterial": "РЕЗИНА",
        "dimensions": "360Х300 ММ",
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Коврик HyperX Fury S Pro M можно рекомендовать любому профессиональному геймеру, для которого особенно важен комфорт управления мышью в жестоких онлайн-сражениях. Он имеет габариты 360 х 300 мм и предлагает игроку большое пространство для движения мыши по специальной тканевой поверхности, оптимальной для мышей с оптическим сенсором. Сверху коврик имеет гладкую поверхность, способствующую свободному скольжению манипулятора, а снизу он снабжен резиновым основанием, которое не позволяет ему двигаться по компьютерному столу. Украшенный логотипом производителя среднего размера черный коврик для мыши HyperX Fury S Pro M можно свернуть в трубочку для большего удобства перевозки в сумке или рюкзаке. Подарив геймеру полный контроль над перемещениями мыши, он станет по-настоящему востребованным и удобным аксессуаром, верным спутником своего владельца. Качественно изготовленный коврик с простроченным краем выдержит долгую и активную эксплуатацию.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/HyperX%20Fury%20Ultra%20RGB%20M_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "THERMALTAKE LEVEL 20 RGB L",
        "brand": "Thermaltake",
        "price": 7200,
        "size": "СРЕДНИЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": true,
        "coating": null,
        "material": null,
        "baseMaterial": "РЕЗИНА",
        "dimensions": "370Х290 ММ",
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Игровой коврик для мыши Level 20 RGB Gaming Mouse Pad создан с применением поверхности обеспечивающей отличною скорость реагирования и точность для максимально сбалансированного игрового процесса. Основание Level 20 RGB Gaming Mouse Pad имеет прорезиненную структуру с особым протектором, что предотвращает скольжение коврика по поверхности стола. Это несомненно, добавляет уверенности в каждом движении.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Thermaltake%20Level%2020%20RGB%20L_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "RAZER GIGANTUS V2",
        "brand": "Razer",
        "price": 2400,
        "size": "СРЕДНИЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": false,
        "coating": null,
        "material": null,
        "baseMaterial": "РЕЗИНА",
        "dimensions": "360Х275 ММ",
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Игровой коврик для мыши Level 20 RGB Gaming Mouse Pad создан с применением поверхности обеспечивающей отличною скорость реагирования и точность для максимально сбалансированного игрового процесса. Основание Level 20 RGB Gaming Mouse Pad имеет прорезиненную структуру с особым протектором, что предотвращает скольжение коврика по поверхности стола. Это несомненно, добавляет уверенности в каждом движении.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Razer%20Gigantus%20V2.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "RAZER GOLIATHUS CHROMA MERCURY",
        "brand": "Razer",
        "price": 8900,
        "size": "ОГРОМНЫЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": true,
        "coating": null,
        "material": null,
        "baseMaterial": "РЕЗИНА",
        "dimensions": "920Х294 ММ",
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Игровой коврик Razer Goliathus Chroma Mercury благодаря огромным размерам 92x29.4 см позволит разместить на нем клавиатуру вместе с мышкой. При этом устройства не будут мешать друг другу и вам даже при активной игре. Тканевое покрытие гарантирует точный отклик любой модели мыши и типа сенсора на команды и малейшие движения. Изделие Razer Goliathus Chroma Mercury представлено в серой расцветке, а также дополнено яркой RGB-подсветкой с питанием по облегченному кабелю в оплетке 2.1 м и синхронизацией между устройствами. Это превращает обычный коврик в стильный элемент декора. Аксессуар дополнен балансом контроля и скорости, поддержкой Razer Synapse 3, а также удобным креплением для фиксации шнура компьютерной мыши.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Razer%20Goliathus%20Chroma%20Mercury.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "RAZER GIGANTUS V2",
        "brand": "Razer",
        "price": 5200,
        "size": "ОГРОМНЫЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": true,
        "coating": null,
        "material": null,
        "baseMaterial": "РЕЗИНА",
        "dimensions": "940Х410 ММ",
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Коврик Razer Gigantus V2 [RZ02-03330400-R3M1] − удобный аксессуар прямоугольной формы, обладающий размерами 940x410x4 мм. Его толщина 4 мм обеспечивает высокую прочность изделия при сохранении комфорта эксплуатации: коврик будет почти не ощутим для пользователя. Верхнее покрытие по технологии speed + control изготавливается из мягкой и эластичной ткани, которая обладает плотной фактурой. Это способствует легкости и высокой скорости скольжения. При этом, точность скольжения сохраняется. Коврик Razer Gigantus V2 [RZ02-03330400-R3M1] ложится на резиновое основание, которое исключает его смещение даже при интенсивных движениях мышью. Пенный наполнитель, размещенный между тканевым и резиновым покрытиями, позволяет коврику оставаться плоским и ровным на любых поверхностях. Аксессуар будет одинаково эффективен для манипуляторов с любой чувствительностью сенсора.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Razer%20Gigantus%20V2%201.png",
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Newbie%201/Newbie%201.jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Newbie%201.png",
        "title": "NEWBIE 1",
        "typebuilds": "NEWBIE",
        "price": 54000,
        "description1": "55 FPS на средне-высоких настройках графики",
        "description2": "Для рабочих задач начального уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Хорошее решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 4,
        "ozu": "16 ГБ",
        "videoCart": "GeForce GTX 1650",
        "processor": "Intel Core i3-10100",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Newbie%202/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Newbie%202.jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Newbie%202.png",
        "title": "NEWBIE 2",
        "typebuilds": "NEWBIE",
        "price": 62000,
        "description1": "60 FPS на средне-высоких настройках графики",
        "description2": "Для рабочих задач начального уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Хорошее решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 4,
        "ozu": "16 ГБ",
        "videoCart": "GeForce GTX 1660 super",
        "processor": "Intel Core i3-10100",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Newbie%203/Bez-imeni-1.jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Newbie%203/Newbie%202%20(1).png",
        "title": "NEWBIE 3",
        "typebuilds": "NEWBIE",
        "price": 71000,
        "description1": "60 FPS на средне-высоких настройках графики",
        "description2": "Для рабочих задач начального уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Хорошее решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 4,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 3050 Dual",
        "processor": "Intel Core i3-10100",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Newbie%204/Newbie%204%20(1).jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Newbie%204%20(2).png",
        "title": "NEWBIE 4",
        "typebuilds": "NEWBIE",
        "price": 75800,
        "description1": "60 FPS на средне-высоких настройках графики",
        "description2": "Для рабочих задач начального уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Хорошее решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 4,
        "ozu": "16 ГБ",
        "videoCart": "AMD Radeon RX 6600 Fighter",
        "processor": "Intel Core i3-12100",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Standard%201/Standard%201.jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Standard%201/Standard%201%20(main).png",
        "title": "STANDARD 1",
        "typebuilds": "STANDART",
        "price": 82000,
        "description1": "60 FPS на высоких настройках графики",
        "description2": "Для рабочих задач среднего уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 6,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 2060 OC",
        "processor": "Intel Core i5-10400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Standart%202/Standart%202.jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Standart%202/Standart_2-removebg-preview.png",
        "title": "STANDARD 2",
        "typebuilds": "STANDART",
        "price": 87000,
        "description1": "65 FPS на высоких настройках графики",
        "description2": "Для рабочих задач среднего уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 6,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 3060 GAMING",
        "processor": "Intel Core i5-10400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Standard%203/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Standard%203%20(1).jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Standard%203/Standard%203%20(Main).png",
        "title": "STANDARD 3",
        "typebuilds": "STANDART",
        "price": 88000,
        "description1": "75 FPS на высоких настройках графики",
        "description2": "Для рабочих задач среднего уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 6,
        "ozu": "16 ГБ",
        "videoCart": "AMD Radeon RX 6650 XT",
        "processor": "Intel Core i5-10400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Standard%204/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Standard%204%20(1).jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Standard%204/Standard%204%20(main).png",
        "title": "STANDARD 4",
        "typebuilds": "STANDART",
        "price": 90000,
        "description1": "85 FPS на ультра-высоких настройках графики",
        "description2": "Для рабочих задач среднего уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 6,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 3060",
        "processor": "Intel Core i5-10400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Pro%201/Pro%201%20(1).jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Pro%201/Pro%201%20(main).png",
        "title": "PRO 1",
        "typebuilds": "PRO",
        "price": 98000,
        "description1": "78 FPS на ультра настройках графики",
        "description2": "Для рабочих задач высокого уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 6,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 3060",
        "processor": "Intel Core i5-12400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Pro%202/Pro%202%20(1).jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Pro%202/Pro%202.png",
        "title": "PRO 2",
        "typebuilds": "PRO",
        "price": 110000,
        "description1": "75 FPS на ультра настройках графики",
        "description2": "Для рабочих задач среднего уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 6,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 3060 Ti",
        "processor": "Intel Core i5-12400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Pro%205/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Bez-imeni-1%20(1).jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Pro%205.png",
        "title": "PRO 3",
        "typebuilds": "PRO",
        "price": 121000,
        "description1": "100 FPS на ультра настройках графики",
        "description2": "Для рабочих задач высокого уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 6,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 3070",
        "processor": "Intel Core i5-12400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Pro%204/Pro%204.jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Pro%204/Pro%204%20(main).png",
        "title": "PRO 4",
        "typebuilds": "PRO",
        "price": 140000,
        "description1": "115 FPS на ультра настройках графики",
        "description2": "Для рабочих задач высокого уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 10,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 3070",
        "processor": "Intel Core i5-13400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "GraphTable",
        "image": "https://lightflightpc.ru/uploads/Devices/Graphictablet/HUION%20H420_preview.png",
        "title": "HUION H420",
        "brand": "Huion",
        "price": 4100,
        "description": "Графический планшет HUION H420 представлен в черной расцветке, весит 0.12 кг и имеет габариты 17.6х11.5 при толщине всего 0.75 см. Используется проводной тип подключения к компьютеру при помощи USB-интерфейса. Предусматривается поддержка наиболее популярных ОС. Поставка осуществляется с фирменным ПО, USB-кабелем и пером с набором наконечников. Модель HUION H420 подходит для правшей и левшей. Используется беспроводное перо с 2048 уровнями чувствительности. Габариты рабочей зоны составляют 10.2х5.7 см. Время отклика составляет 200 точек в секунду. Планшет дополнен тремя кнопками управления. Данное устройство нашло применение среди фотографов, художников и инженеров.",
        "inteface": "USB",
        "conectiontype": "ПРОВОДНОЙ",
        "color": "ЧЕРНЫЙ",
        "inputmethod": "ПЕРЬЕВОЙ",
        "workspacesize": "121.9X76.2",
        "permission": "4000 LPI",
        "maximumpenpeadingheight": "12 MM",
        "responsetime": "200 ТОЧЕК В СЕКУНДУ",
        "pentype": "БЕСПРОВОДНОЕ",
        "id": uuid(),
    },
    {
        "type": "GraphTable",
        "image": "https://lightflightpc.ru/uploads/Devices/Graphictablet/Wacom%20One%20by%20Wacom%202%20Small_preview.png",
        "title": "HUION H640P",
        "brand": "HUION",
        "price": 15000,
        "description": "Графический планшет HUION H640P, оборудованный 6 кнопками, порадует вас точностью реакции на силу нажатия. Модель распознает более 8 тысяч уровней силы нажатия. Обеспечивается разрешение, равное 5080 lpi. Размер рабочей области, составляющий 160x100 мм, достаточен для решения большинства задач. Используется проводной тип подключения, с использованием порта USB. Планшет совместим с большинством используемых в настоящее время операционных систем: Windows 7, 8 и 10, а также с Mac OS X 10.11 или выше. Планшет HUION H640P укомплектован беспроводным пером PW100, не требующим подзарядки. Также в комплект поставки устройства включены USB-кабель, подставка для пера и набор наконечников. Компактные размеры планшета (его габариты равны 260x147.7x8 мм) позволят вам носить устройство с комфортом везде, где это будет необходимо. Масса корпуса модели невелика: она равна 227 г.",
        "inteface": "USB",
        "conectiontype": "БЕСПРОВОДНОЙ",
        "color": "ЧЕРНЫЙ",
        "inputmethod": "ПЕРЬЕВОЙ",
        "workspacesize": "160ММ100",
        "permission": "5080 LPI",
        "responsetime": "233 ТОЧЕК В СЕКУНДУ",
        "maximumpenpeadingheight": "10 MM",
        "pentype": "БЕСПРОВОДНОЕ",
        "numberofbuttons": "6 ШТ",
        "id": uuid(),
    },
    {
        "type": "GraphTable",
        "image": "https://lightflightpc.ru/uploads/Devices/Graphictablet/HUION%20HS610_preview.png",
        "title": "HUION HS610",
        "brand": "HUION",
        "price": 14800,
        "description": "Графический планшет HUION HS610 оснащен активной областью 10x6 дюймов и предлагает все необходимое для рисования. Планшет поставляется с беспроводным пером, которое обладает 8192 уровнями чувствительности к нажатиям и чувствительностью к наклону в пределах 60 градусов, что гарантирует комфорт в процессе рисования. Максимальная высота считывания пера составляет 10 мм. Панель с сенсорным кольцом и 12 программируемыми клавишами обеспечивает простое управление. Графический планшет HUION HS610 может подключаться к ПК или ноутбуку посредством USB-кабеля, а также к смартфону под управлением Android. Выполненное в компактном корпусе, устройство обеспечивает удобство пользования и транспортировки.",
        "inteface": "USB",
        "conectiontype": "ПРОВОДНОЙ",
        "color": "ЧЕРНЫЙ",
        "inputmethod": "ПЕРЬЕВОЙ",
        "workspacesize": "254X158.8 ММ",
        "permission": "5080 LPI",
        "responsetime": "266 ТОЧЕК В СЕКУНДУ",
        "maximumpenpeadingheight": "10 MM",
        "pentype": "БЕСПРОВОДНОЕ",
        "numberofbuttons": "6 ШТ",
        "id": uuid(),
    },
    {
        "type": "GraphTable",
        "image": "https://lightflightpc.ru/uploads/Devices/Graphictablet/HUION%20HS611%20Red_preview.png",
        "title": "HUION HS611 RED",
        "brand": "HUION",
        "price": 17200,
        "description": "Графический планшет HUION HS611 Red выполнен в корпусе кораллово-красного цвета и обладает компактными размерами. Беспроводное перо поддерживает 8192 уровня чувствительности к нажатиям и обладает чувствительностью к наклону в пределах 60 градусов, что гарантирует комфорт в процессе рисования. Максимальная высота считывания пера составляет 10 мм. Частота отклика 266 PPS обеспечивает быструю и плавную реакцию на перо. Планшет HUION HS611 Red позволяет управлять фоновой музыкой и переключаться между программами без прерывания рабочего процесса. Панель с сенсорным кольцом и 10 программируемыми клавишами обеспечивает простое управление. Подключение устройства осуществляется через порт USB Type-C. Отмечается совместимость с ПК и ноутбуками, а также мобильными устройствами под управлением Android.",
        "inteface": "USB TYPE-C",
        "conectiontype": "ПРОВОДНОЙ",
        "color": "КРАСНЫЙ",
        "inputmethod": "ПЕРЬЕВОЙ",
        "workspacesize": "258X161 ММ",
        "permission": "5080 LPI",
        "maximumpenpeadingheight": "10 MM",
        "pentype": "БЕСПРОВОДНОЕ",
        "numberofbuttons": "6 ШТ",
        "id": uuid(),
    },
    {
        "type": "GraphTable",
        "image": "https://lightflightpc.ru/uploads/Devices/Graphictablet/HUION%20Q620M%20Black_preview.png",
        "title": "HUION Q620M BLACK",
        "brand": "HUION",
        "price": 20500,
        "description": "Изготовленный из высококачественного пластика и металла, графический планшет HUION Q620M отличается исключительным эстетическим дизайном и изысканным качеством исполнения. Dial-контроллер совместим с протоколом Windows Radial Controller. Функции Dial-контроллера могут программироваться в меню драйвера по умолчанию. В то время как функции Windows Radial будут активированы после выбора «Использовать Windows Radial» в меню драйвера. Длительно нажмите клавишу в центре Dial-контроллера, чтобы вызвать меню инструментов. Dial-контроллер, также может использоваться для регулировки размера кисти, выбора цвета, прокрутки страниц и т. д. Кроме того, рабочая область 10,5 х 6,5 дюйма – это огромный холст для творчества. Экспресс-клавиши HUION Q620M обеспечивают более простой и быстрый подход к реализации Ваших идей. HUION Q620M можно заряжать от источника питания 5 В, 500 мА или 5 В, 1 А, Время автономной работы - 20 часов. Время до полной зарядки - 1 ч. 20 мин.",
        "inteface": "USB TYPE-C",
        "conectiontype": "ПРОВОДНОЙ/БЕСПРОВОДНОЙ",
        "color": "ЧЕРНЫЙ",
        "inputmethod": "ПЕРЬЕВОЙ",
        "workspacesize": "266X166 ММ",
        "permission": "5080 LPI",
        "responsetime": "266 ТОЧЕК В СЕКУНДУ",
        "maximumpenpeadingheight": "10 MM",
        "pentype": "БЕСПРОВОДНОЕ",
        "numberofbuttons": "6 ШТ",
        "id": uuid(),
    },
    {
        "type": "GraphTable",
        "image": "https://lightflightpc.ru/uploads/Devices/Graphictablet/Wacom%20One%20by%20Wacom%202%20Small_preview.png",
        "title": "WACOM ONE BY WACOM 2 SMALL",
        "brand": "WACOM",
        "price": 6600,
        "description": "Графический планшет Wacom One 2 Small станет незаменимым устройством для того, кто привык всю информацию запоминать в графическом виде. Размеры его рабочей области (152х95 мм) позволяют работать с достаточным комфортом для глаз. Информация на экран вводится сенсорным образом. Кроме того, устройство дополнено беспроводным пером с 2048 уровнями чувствительности и сменными наконечниками. Время отклика модели составляет 133 точки в секунду, разрешение экрана – 2540 lpi. Вес планшета – всего 240 г. Модель Wacom One 2 Small уникальна тем, что может использоваться и правшами, и левшами.",
        "inteface": "USB",
        "conectiontype": "ПРОВОДНОЙ",
        "color": "ЧЕРНЫЙ",
        "inputmethod": "ПЕРЬЕВОЙ",
        "workspacesize": "152X95 ММ",
        "permission": "2540 LPI",
        "responsetime": "133 ТОЧЕК В СЕКУНДУ",
        "pentype": "БЕСПРОВОДНОЕ",
        "id": uuid(),
    },
    {
        "type": "GraphTable",
        "image": "https://lightflightpc.ru/uploads/Devices/Graphictablet/Wacom%20Intuos%20S%20Bluetooth%20CTL-4100WLE-N_preview.png",
        "title": "WACOM INTUOS S BLUETOOTH CTL-4100WLE-N",
        "brand": "WACOM",
        "price": 12400,
        "description": "Графический планшет Wacom Intuos S Bluetooth CTL-4100WLE-N характеризуется наличием беспроводного пера, особенность которого заключается в том, что оно не требует периодической подзарядки. Благодаря компактным размерам вам не составит труда взять планшет с собой, чтобы реализовывать творческие порывы в любом месте. Еще одно достоинство Wacom Intuos S Bluetooth CTL-4100WLE-N заключается в высокой чувствительности и быстром отклике пера на касание. Таким образом, у вас получатся невероятно четкие и хорошо прорисованные линии. Для пера предусмотрено несколько наконечников и пинцет для их замены, что позволит воплотить в реальность любую задумку.",
        "inteface": "BLUETOOTH",
        "conectiontype": "БЕСПРОВОДНОЙ",
        "color": "ЗЕЛЁНЫЙ, ЧЕРНЫЙ",
        "inputmethod": "ПЕРЬЕВОЙ",
        "workspacesize": "152X95 ММ",
        "permission": "2540 LPI",
        "maximumpenpeadingheight": "7 MM",
        "responsetime": "133 ТОЧЕК В СЕКУНДУ",
        "pentype": "БЕСПРОВОДНОЕ",
        "id": uuid(),
    },
    {
        "type": "GraphTable",
        "image": "https://lightflightpc.ru/uploads/Devices/Graphictablet/Wacom%20Intuos%20M%20Bluetooth%20CTL-6100WLK-N_preview.png",
        "title": "Wacom Intuos M Bluetooth CTL-6100WLK-N",
        "brand": "WACOM",
        "price": 23800,
        "description": "Графический планшет Wacom Intuos M Bluetooth CTL-6100WLK-N комплектуется беспроводным пером, которое не требует периодической подзарядки. Его особенность заключается в высокой чувствительности и быстром отклике на силу нажатия, благодаря чему вы сможете добиться идеально ровных и четких линий при создании рисунков. Сменные наконечники позволяют реализовывать наиболее смелые творческие задумки. Для их замены в комплекте предусмотрен специальный пинцет. Компактный дизайн модели Wacom Intuos M Bluetooth CTL-6100WLK-N позволит вам поместить ее в небольшую сумку, чтобы сделать необходимую заметку или набросок в любом месте.",
        "inteface": "BLUETOOTH",
        "conectiontype": "БЕСПРОВОДНОЙ",
        "color": "ЧЕРНЫЙ",
        "inputmethod": "ПЕРЬЕВОЙ",
        "workspacesize": "216X135 ММ",
        "permission": "2540 LPI",
        "maximumpenpeadingheight": "7 MM",
        "responsetime": "133 ТОЧЕК В СЕКУНДУ",
        "pentype": "БЕСПРОВОДНОЕ",
        "id": uuid(),
    },
    {
        "type": "GraphTable",
        "image": "https://lightflightpc.ru/uploads/Devices/Graphictablet/XP-PEN%20Star%20G430S_preview.png",
        "title": "XP-PEN STAR G430S",
        "brand": "XP-PEN",
        "price": 4500,
        "description": "Графический планшет XP-PEN Star G430S при своих компактных размерах и массе 130 г всегда будет под рукой. Это значит, что пользователь может реализовывать свой потенциал тогда, когда это будет удобно. Рабочая область экрана модели составляет 120х77 мм при разрешении 5080 lpi. При этом беспроводное перо имеет 8192 уровня чувствительности к нажатию, что позволяет рисовать всевозможные скетчи, аниме и варьировать толщину линии. Графический планшет XP-PEN Star G430S поставляется вместе с 10 сменными насадками для стилуса и зажимом. Проводная модель совместима со всеми устройствами на ОС Mac и Windows. Толщина планшета – всего 2 мм.",
        "inteface": "USB",
        "conectiontype": "ПРОВОДНОЙ",
        "color": "ЧЕРНЫЙ",
        "inputmethod": "ПЕРЬЕВОЙ",
        "workspacesize": "120X77 ММ",
        "permission": "5080 LPI",
        "maximumpenpeadingheight": "10 MM",
        "responsetime": "266 ТОЧЕК В СЕКУНДУ",
        "pentype": "БЕСПРОВОДНОЕ",
        "id": uuid(),
    },
    {
        "type": "GraphTable",
        "image": "https://lightflightpc.ru/uploads/Devices/Graphictablet/XP-PEN%20Star%20G430S_preview.png",
        "title": "XP-PEN Deco Pro S",
        "brand": "XP-PEN",
        "price": 12700,
        "description": "Графический планшет XP-PEN Deco Pro S может с успехом использоваться пользователями любого уровня квалификации. Устройство способно проявить свою эффективность при решении задач профессионального уровня. Планшет обладает исключительно удобной панелью управления, центральным элементом которой является двойное колесо с функцией трекпада. Общее количество кнопок – 8. Планшет не только отличается крайне малой толщиной, но и имеет невысокую массу. Размер рабочей области планшета XP-PEN Deco Pro S – 230x130 мм. Разрешение – 5080 lpi. Способ ввода традиционный – с помощью беспроводного пера. Устройство распознает 8192 уровня чувствительности к нажатию. Точность пера – 0.25 мм. Интерфейс подключения планшета – USB Type-C. Модель поддерживается не только Windows и Mac OS X, но и Android. В комплектацию устройства входят держатель для пера, документация, переходники USB, перо, перчатка и сменная насадка. В дизайне планшета используется традиционное для техники рассматриваемого типа сочетание черного и серебристого цветов.",
        "inteface": "USB TYPE-C",
        "conectiontype": "ПРОВОДНОЙ",
        "color": "СЕРЕБРИСТЫЙ, ЧЕРНЫЙ",
        "inputmethod": "ПЕРЬЕВОЙ",
        "workspacesize": "230X130 ММ",
        "permission": "5080 LPI",
        "maximumpenpeadingheight": "10 MM",
        "responsetime": "200 ТОЧЕК В СЕКУНДУ",
        "pentype": "БЕСПРОВОДНОЕ",
        "id": uuid(),
    },
    {
        "type": "GraphTable",
        "image": "https://lightflightpc.ru/uploads/Devices/Graphictablet/XP-PEN%20Artist%2012%20PRO_preview.png",
        "title": "XP-PEN ARTIST 12 PRO",
        "brand": "XP-PEN",
        "price": 38200,
        "description": "Графический планшет-монитор XP-PEN Artist 12 PRO предназначен для моделирования, архитектурного дизайна, рисования и других творческих процессов. В планшете реализована технология полной ламинации с органичным сочетанием стекла и экрана, что создает комфортные рабочие условия без бликов. Экран с диагональю 11.6 дюймов, разрешением FullHD и углами обзора 178 градусов обеспечивает детализированное изображение с реалистичной цветопередачей. Графический планшет XP-PEN Artist 12 PRO поставляется с пером, которое благодаря 8192 уровням чувствительности к нажатиям гарантирует максимальную точность управления и производительность творческого процесса. Поддержка функции наклона пера позволяет быстро и легко реагировать на движения руки. Устройство также оснащено 8 программируемыми кнопками быстрого доступа и предлагает множество вариантов настройки. Универсальный кабель 3 в 1 способствует удобному подключению интерактивного планшета-монитора.",
        "inteface": "USB ",
        "conectiontype": "ПРОВОДНОЙ",
        "color": " ЧЕРНЫЙ",
        "maximumscreenresolution": "1920X1080",
        "inputmethod": "ПЕРЬЕВОЙ",
        "workspacesize": "256.32X144.18",
        "permission": "5080 LPI",
        "maximumpenpeadingheight": "10 MM",
        "pentype": "БЕСПРОВОДНОЕ",
        "id": uuid(),
    },
    {
        "type": "HeadPhone",
        "image": "https://lightflightpc.ru/uploads/cpucooling/Apple%20AirPods%20Max%20green.png",
        "title": "APPLE AIRPODS MAX GREEN",
        "brand": "APPLE",
        "price": 69500,
        "description": "AirPods Max полностью меняют представление о полноразмерных наушниках. Динамический драйвер, разработанный Apple, способен воспроизводить захватывающий звук высокой чёткости. Каждая деталь, от оголовья до амбушюров, разработана для полного комфорта. Передовая функция активного шумоподавления блокирует внешние шумы, а Прозрачный режим позволяет слышать окружающий мир. Кроме того, благодаря пространственному аудио и функции динамического отслеживания движений головы, создаётся ощущение такого же объёмного звука, как в кинотеатре",
        "color": "ЗЕЛЕНЫЙ",
        "signaltransmissionmethod": "BLUETOOTH",
        "Sound scheme format": "2.0",
        "backlight": "НЕТ",
        "sensitivity": "127 ДБ",
        "microphone": "ЕСТЬ",
        "microphonesensitivity": "-40 ДБ",
        "functionsandfeaturesofthemicrophone": "В КОРПУСЕ",
        "wiredconnectiontype": "НЕТ",
        "lengthofcable": "НЕТ",
        "id": uuid(),
    },
    {
        "type": "HeadPhone",
        "image": "https://lightflightpc.ru/uploads/Devices/Headphones/Asus%20Cerberus%20V2%20%D0%BA%D1%80%D0%B0%D1%81%D0%BD%D1%8B%D0%B9_preview.png",
        "title": "ASUS CERBERUS V2 КРАСНЫЙ",
        "brand": "ASUS",
        "price": 4300,
        "color": "КРАСНЫЙ",
        "soundschemeformat": "2.0",
        "backlight": "НЕТ",
        "description": "Наушники Asus Cerberus V2 станут великолепным выбором для любителей видеоигр. Конструкция этого высококлассного устройства, начиная от «начинки», и заканчивая внешними атрибутами, оптимизирована для участия в игровом процессе. От вас не ускользнет никакой, даже мельчайший звуковой нюанс игры. Полноразмерные амбушюры защитят ваш слух от посторонних звуков. Используя регулируемое оголовье, вы сможете с высокой точностью выбрать удобное положение наушников на голове. Наушники Asus Cerberus V2 воспроизводят звук в диапазоне от 20 до 20000 Гц. Устройство подойдет и для прослушивания музыки. Яркой особенностью модели является наличие 2 микрофонов, один из которых предназначен для игр, а второй – для использования наушников в роли гарнитуры. Очень удобен регулятор громкости звучания. Подключение наушников происходит с помощью наиболее широко распространенного разъема мини-джек. Длина аудиокабеля составляет 1.2 м. Тканевая оплетка не только защищает кабель от механических воздействий, но и придает аксессуару привлекательности.",
        "wiredconnectiontype":"2X JACK 3.5 ММ, JACK 3.5 ММ",
        "microphone": "ЕСТЬ",
        "minimumrepeatablefrequency":"20 ГЦ",
        "Maximum playback frequency":"20000 ГЦ",
        "microphonesensitivity": "-40 ДБ",
        "functionsandfeaturesofthemicrophone": "В КОРПУСЕ",
        "wiredconnectiontype": "НЕТ",
        "lengthofcable": "1.3 М",
        "id": uuid(),
    },
    {
        "type": "HeadPhone",
        "image": "https://lightflightpc.ru/uploads/Devices/Headphones/Asus%20TUF%20Gaming%20H3%20Red.png",
        "title": "ASUS TUF GAMING H3 RED",
        "brand": "ASUS",
        "price": 4700,
        "color": "КРАСНЫЙ",
        "sensitivity":"100 ДБ",
        "soundschemeformat": "7.1",
        "backlight": "НЕТ",
        "description": "Проводные наушники Asus TUF Gaming H3 - неотъемлемый атрибут успешного прохождения видеоигр. Модель готова обеспечить геймера максимально точным позиционированием, благодаря которому он сможет услышать малейшие шорохи и направление, с которого они доносятся, чтобы определить местоположение врага. Благодаря герметичным акустическим камерам игрок сможет ощутить эффект полного погружения в происходящее в игре, наслаждаясь реалистичными аудиоэффектами. Длительные игровые сессии не станут причиной дискомфорта благодаря малому весу гарнитуры, не превышающему 294 г. Проводные наушники Asus TUF Gaming H3 обладают прочной конструкцией, обеспеченной металлическим корпусом, благодаря чему они смогут выдержать самое интенсивное использование. Неоспоримым преимуществом модели стал формат звуковой схемы 7.1, гарантирующий объемный и многогранный звук с максимальной детализацией. Представленная в эффектном красно-черном цвете гарнитура располагает динамическими излучателями с 50-миллиметровыми мембранами, обеспечивающими воспроизведение звука в диапазоне частот 20-20000 Гц. Благодаря закрытому акустическому оформлению звуки извне не будут отвлекать вас от прохождения игр.",
        "wiredconnectiontype":"2X JACK 3.5 ММ , JACK 3.5 ММ",
        "microphone": "ЕСТЬ",
        "microphonesensitivity": "-40 ДБ",
        "functionsandfeaturesofthemicrophone": "ОДНОНАПРАВЛЕННЫЙ МИКРОФОН , СЪЕМНЫЙ МИКРОФОН",
        "lengthofcable": "1.3 М",
        "id": uuid(),
    },
    {
        "type": "HeadPhone",
        "image": "https://lightflightpc.ru/uploads/Devices/Headphones/Asus%20TUF%20Gaming%20H7%20Core%20Gray.png",
        "title": "ASUS TUF GAMING H7 CORE GRAY",
        "brand": "ASUS",
        "price": 7200,
        "color": "СЕРЫЙ",
        "soundschemeformat": "2.0",
        "backlight": "НЕТ",
        "description": "Проводные наушники Asus TUF Gaming H7 Core представляют собой функциональную игровую модель черного цвета с металлическим корпусом и мягкими амбушюрами из устойчивой к износу экокожи. Устройство оснащено закрытой акустикой и динамическими излучателями. Имеется съемный подвижный микрофон двойного типа однонаправленного действия. Прибор Asus TUF Gaming H7 Core дополнен удобным регулятором громкости и кнопкой для активации и отключения микрофона. Кабель длиной 1.2 м оснащен плотной тканевой оплеткой и позолоченным стандартным аудиоразъемом. Также поставка осуществляется с удлинительным кабелем длиной 1.3 м со штекером 2x jack 3.5 mm. Данная модель совместима с Xbox, PS.",
        "microphone": "ЕСТЬ",
        "sensitivity": "100 ДБ",
        "microphonesensitivity": "-40 ДБ",
        "functionsandfeaturesofthemicrophone": "ОДНОНАПРАВЛЕННЫЙ МИКРОФОН , ДВОЙНОЙ МИКРОФОН , СЪЕМНЫЙ МИКРОФОН",
        "wiredconnectiontype": "НЕТ",
        "lengthofcable": "1.2 М",
        "id": uuid(),
    },
    {
        "type": "HeadPhone",
        "image": "https://lightflightpc.ru/uploads/Devices/Headphones/Corsair%20HS35%20%D1%87%D0%B5%D1%80%D0%BD%D1%8B%D0%B9_preview.png",
        "title": "CORSAIR HS35 ЧЕРНЫЙ",
        "brand": "CORSAIR", 
        "price": 6800,
        "color": "ЧЕРНЫЙ",
        "soundschemeformat": "2.0",
        "backlight": "НЕТ",
        "description": "Проводные наушники Corsair HS35 охватывающего типа идеально подходят для компьютерных игр. Ведь в них отлично слышно каждый звук, что позволит более эффективно ориентироваться в игре. Этому способствуют 50-миллиметровые мембраны неодимовых динамиков, которые обладают чувствительностью 113 дБ и воспроизводят звук в диапазоне 20-20000 Гц. Мягкие амбушюры и мягкое оголовье предусматривают довольно комфортное нахождение в наушниках. Проводные наушники Corsair HS35 оснащены съемным микрофоном на подвижном креплении, что позволит переговариваться в процессе игры с другими игроками. Высокая чувствительность (-40 дБ) микрофона и шумоподавление обеспечивают передачу четкого звука даже при нахождении игрока в шумном помещении. Функциональные кнопки и регулятор громкости находятся на корпусе одного из наушников. Технические параметры наушников делают их совместимыми с PS и Xbox. Очень длинный провод (1.8 м) с разъемом jack 3.5 мм позволяет находиться на удалении от компьютера или приставки.",
        "microphone": "ЕСТЬ",
        "sensitivity": "113 ДБ",
        "microphonesensitivity": "-40 ДБ",
        "functionsandfeaturesofthemicrophone": "ОДНОНАПРАВЛЕННЫЙ МИКРОФОН , ДВОЙНОЙ МИКРОФОН , СЪЕМНЫЙ МИКРОФОН",
        "wiredconnectiontype": "НЕТ",
        "lengthofcable": "1.8 М",
        "id": uuid(),
    },
]