import { BiWifi, BiBluetooth } from 'react-icons/bi'
import {v4 as uuid} from "uuid"


export const products = [
    {
        "type": "Rug",
        "title": "ASUS TUF GAMING P3",
        "brand": "Asus",
        "price": 2400,
        "size": "СРЕДНИЙ",
        "color": "СЕРЫЙ",
        "backlight": false,
        "coating": "Speed + Control",
        "material": "ТКАНЬ",
        "baseMaterial": "РЕЗИНА",
        "dimensions": null,
        "wireless charger": null,
        "additionalInformation": null,
        "description": "TUF Gaming P3 – это прочный коврик для мыши с гладкой тканевой поверхностью, обеспечивающей высокую точность позиционирования. Он оформлен в стиле серии TUF Gaming, обладает простроченными краями и резиновой основой и прекрасно подходит для игр любых жанров. Идеально гладкая тканевая поверхность коврика TUF Gaming P3 прекрасно подходит для игр. Мышь скользит по нему без малейших усилий, позволяя достичь высокой скорости и точности позиционирования, которые так необходимы для победы.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/ASUS%20TUF%20Gaming%20P3_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "ASUS ROG Sheath PINK",
        "brand": "Asus",
        "price": 4400,
        "size": "ОГРОМНЫЙ",
        "color": "ГОЛУБОЙ",
        "backlight": false,
        "coating": null,
        "material": "ТКАНЬ",
        "baseMaterial": "РЕЗИНА",
        "dimensions": "900Х440 ММ",
        "wireless charger": false,
        "additionalInformation": null,
        "description": "Мягкий тканевый коврик для мыши с большой и гладкой поверхностью, противоскользящим основанием и простроченными краями",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/ASUS%20ROG%20Sheath%20PINK_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "ASUS ROG BALTEUS",
        "brand": "Asus",
        "price": 12400,
        "size": "СРЕДНИЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": true,
        "coating": null,
        "material": null,
        "baseMaterial": "РЕЗИНА",
        "dimensions": "370Х320 ММ",
        "wireless charger": false,
        "additionalInformation": "USB - РАЗЪЕМ ДЛЯ ПОДКЛЮЧЕНИЯ ДОПОЛНИТЕЛЬНЫХ УСТРОЙСТВ",
        "description": "Коврик ASUS ROG Balteus применяется для обеспечения точности работы компьютерной мыши в процессе игры. Предмет выполнен в сером цвете с рисунком логотипа. Материал изготовления – резина, что обеспечивает отсутствие скольжения коврика при движении руки. ASUS ROG Balteus не оснащен подставкой под запястье, беспроводной зарядкой, обладает подсветкой. Размер – средний, параметры составляют 370x320x7.9 мм. Дополнительными опциями являются USB-разъем для подключения дополнительных устройств, 15-зонная подсветка Aura.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/ASUS%20ROG%20Balteus%20(1).png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "ASUS NH01 ROG BALTEUS QI",
        "brand": "Asus",
        "price": 12400,
        "size": "СРЕДНИЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": true,
        "coating" :  null,
        "material": null,
        "baseMaterial": "РЕЗИНА",
        "dimensions": "370Х320 ММ",
        "wireless charger": false,
        "additionalInformation": "USB - РАЗЪЕМ ДЛЯ ПОДКЛЮЧЕНИЯ ДОПОЛНИТЕЛЬНЫХ УСТРОЙСТВ",
        "description": "Коврик ASUS ROG Balteus применяется для обеспечения точности работы компьютерной мыши в процессе игры. Предмет выполнен в сером цвете с рисунком логотипа. Материал изготовления – резина, что обеспечивает отсутствие скольжения коврика при движении руки. ASUS ROG Balteus не оснащен подставкой под запястье, беспроводной зарядкой, обладает подсветкой. Размер – средний, параметры составляют 370x320x7.9 мм. Дополнительными опциями являются USB-разъем для подключения дополнительных устройств, 15-зонная подсветка Aura.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Asus%20NH01%20ROG%20BALTEUS%20QI.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "BLIZZARD OVERWATCH CHARACTER ICON",
        "brand": "Blizzard",
        "price": 2900,
        "size": "СРЕДНИЙ",
        "color": "РАЗНОЦВЕТНЫЙ",
        "backlight": false,
        "coating": null,
        "material": "ПОЛИЭСТЕР",
        "baseMaterial": "КАУЧУК",
        "dimensions": "350Х240 ММ",
        "wirelesscharger": false,
        "additionalInformation": null,
        "description": "Коврик для мыши Character Icon даст вашим быстрым щелчкам и разрушительным ударам в голову красочную основу. Оживите свое игровое пространство, добавив его в свою коллекцию Overwatch. Ковёр Overwatch Character Icon специально разработан для фанатов игры Overwatch. Покрытие коврика выполнено из плотной ткани, которая усиливает чувствительность взаимодействия игровой мыши с поверхностью. Резиновое основание не даёт коврику скользить по столу, когда вы активно двигаете рукой. Износостойкие края с гладкой прострочкой предотвращают преждевременный износ при ежедневном использовании. С целью уменьшения частоты стирки производитель рекомендует через день протирать изделие влажными салфетками.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Blizzard%20Overwatch%20Character%20Icon_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "CORSAIR MM200 CLOTH GAMING MOUSE MAT - MEDIUM",
        "brand": "Crosair",
        "price": 1900,
        "size": "СРЕДНИЙ",
        "color": "ОСНОВНОЙ ЦВЕТ",
        "backlight": false,
        "coating": "SPEED",
        "material": "ТКАНЬ",
        "baseMaterial": "РЕЗИНА",
        "dimensions": null,
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Коврик Corsair MM200 Cloth Gaming Mouse Mat - Medium – это надежный аксессуар, разработанный специально для того, чтобы вы могли получить абсолютный комфорт в процессе игры. Модель с покрытием speed гарантирует плавное и точное скольжение мыши. Изготовлен коврик из высококачественной ткани, которая гарантирует долговечность и износостойкость даже при ежедневной интенсивной эксплуатации. Резиновая основа Corsair MM200 Cloth Gaming Mouse Mat - Medium обеспечивает прекрасное сцепление с поверхностью, поэтому коврик не скользит даже в процессе интенсивных манипуляций. Коврик обладает средними размерами 360X300X2 мм, что позволяет вам получить достаточно большую область для управления мышью. Аксессуар предусматривает небольшой вес, что наряду с удобной упаковкой способствует комфортной транспортировке. Ярким акцентом на черном полотне является желтая полоса, которую разделяет логотип.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Corsair%20MM200%20Cloth%20Gaming%20Mouse%20Mat%20-%20Medium_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "CORSAIR MM200 CLOTH GAMING MOUSE MAT - EXTENDED",
        "brand": "Crosair",
        "price": 3800,
        "size": "ОГРОМНЫЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": false,
        "coating": "SPEED",
        "material": "ТКАНЬ",
        "baseMaterial": "РЕЗИНА",
        "dimensions": null,
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Коврик Corsair MM200 Cloth Gaming Mouse Mat - Medium – это надежный аксессуар, разработанный специально для того, чтобы вы могли получить абсолютный комфорт в процессе игры. Модель с покрытием speed гарантирует плавное и точное скольжение мыши. Изготовлен коврик из высококачественной ткани, которая гарантирует долговечность и износостойкость даже при ежедневной интенсивной эксплуатации. Резиновая основа Corsair MM200 Cloth Gaming Mouse Mat - Medium обеспечивает прекрасное сцепление с поверхностью, поэтому коврик не скользит даже в процессе интенсивных манипуляций. Коврик обладает средними размерами 360X300X2 мм, что позволяет вам получить достаточно большую область для управления мышью. Аксессуар предусматривает небольшой вес, что наряду с удобной упаковкой способствует комфортной транспортировке. Ярким акцентом на черном полотне является желтая полоса, которую разделяет логотип.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Corsair%20MM200%20Cloth%20Gaming%20Mouse%20Mat%20-%20Extended_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "HYPERX FURY S PRO M",
        "brand": "HyperX",
        "price": 1700,
        "size": "СРЕДНИЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": false,
        "coating": "SPEED + Control",
        "material": "ТКАНЬ",
        "baseMaterial": "РЕЗИНА",
        "dimensions": null,
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Коврик HyperX Fury S Pro M можно рекомендовать любому профессиональному геймеру, для которого особенно важен комфорт управления мышью в жестоких онлайн-сражениях. Он имеет габариты 360 х 300 мм и предлагает игроку большое пространство для движения мыши по специальной тканевой поверхности, оптимальной для мышей с оптическим сенсором. Сверху коврик имеет гладкую поверхность, способствующую свободному скольжению манипулятора, а снизу он снабжен резиновым основанием, которое не позволяет ему двигаться по компьютерному столу. Украшенный логотипом производителя среднего размера черный коврик для мыши HyperX Fury S Pro M можно свернуть в трубочку для большего удобства перевозки в сумке или рюкзаке. Подарив геймеру полный контроль над перемещениями мыши, он станет по-настоящему востребованным и удобным аксессуаром, верным спутником своего владельца. Качественно изготовленный коврик с простроченным краем выдержит долгую и активную эксплуатацию.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/HyperX%20Fury%20S%20Pro%20M_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "HYPERX FURY S PRO XL",
        "brand": "HyperX",
        "price": 3900,
        "size": "ОГРОМНЫЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": false,
        "coating": "SPEED + Control",
        "material": "ТКАНЬ",
        "baseMaterial": "РЕЗИНА",
        "dimensions": "900Х420 ММ",
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Коврик HyperX Fury S Pro M можно рекомендовать любому профессиональному геймеру, для которого особенно важен комфорт управ-ления мышью в жестоких онлайн-сражениях. Он имеет габариты 360 х 300 мм и предлагает игроку большое пространство для движения мыши по специальной тканевой поверхности, оптимальной для мышей с оптическим сенсором. Сверху коврик имеет гладкую поверхность, способствующую свободному скольжению манипулятора, а снизу он снабжен резиновым основанием, которое не позволяет ему двигаться по компьютерному столу. Украшенный логотипом производителя среднего размера черный коврик для мыши HyperX Fury S Pro M можно свернуть в трубочку для большего удобства перевозки в сумке или рюкзаке. Подарив геймеру полный контроль над перемещениями мыши, он станет по-настоящему востребованным и удобным аксессуаром, верным спутником своего владельца. Качественно изготовленный коврик с простроченным краем выдержит долгую и активную эксплуатацию.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/HyperX%20Fury%20S%20Pro%20XL_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "HYPERX FURY ULTRA RGB M",
        "brand": "HyperX",
        "price": 8100,
        "size": "СРЕДНИЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": true,
        "coating": "SPEED + Control",
        "material": "ПЛАСТИК",
        "baseMaterial": "РЕЗИНА",
        "dimensions": "360Х300 ММ",
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Коврик HyperX Fury S Pro M можно рекомендовать любому профессиональному геймеру, для которого особенно важен комфорт управления мышью в жестоких онлайн-сражениях. Он имеет габариты 360 х 300 мм и предлагает игроку большое пространство для движения мыши по специальной тканевой поверхности, оптимальной для мышей с оптическим сенсором. Сверху коврик имеет гладкую поверхность, способствующую свободному скольжению манипулятора, а снизу он снабжен резиновым основанием, которое не позволяет ему двигаться по компьютерному столу. Украшенный логотипом производителя среднего размера черный коврик для мыши HyperX Fury S Pro M можно свернуть в трубочку для большего удобства перевозки в сумке или рюкзаке. Подарив геймеру полный контроль над перемещениями мыши, он станет по-настоящему востребованным и удобным аксессуаром, верным спутником своего владельца. Качественно изготовленный коврик с простроченным краем выдержит долгую и активную эксплуатацию.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/HyperX%20Fury%20Ultra%20RGB%20M_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "THERMALTAKE LEVEL 20 RGB L",
        "brand": "Thermaltake",
        "price": 7200,
        "size": "СРЕДНИЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": true,
        "coating": null,
        "material": null,
        "baseMaterial": "РЕЗИНА",
        "dimensions": "370Х290 ММ",
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Игровой коврик для мыши Level 20 RGB Gaming Mouse Pad создан с применением поверхности обеспечивающей отличною скорость реагирования и точность для максимально сбалансированного игрового процесса. Основание Level 20 RGB Gaming Mouse Pad имеет прорезиненную структуру с особым протектором, что предотвращает скольжение коврика по поверхности стола. Это несомненно, добавляет уверенности в каждом движении.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Thermaltake%20Level%2020%20RGB%20L_preview.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "RAZER GIGANTUS V2",
        "brand": "Razer",
        "price": 2400,
        "size": "СРЕДНИЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": false,
        "coating": null,
        "material": null,
        "baseMaterial": "РЕЗИНА",
        "dimensions": "360Х275 ММ",
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Игровой коврик для мыши Level 20 RGB Gaming Mouse Pad создан с применением поверхности обеспечивающей отличною скорость реагирования и точность для максимально сбалансированного игрового процесса. Основание Level 20 RGB Gaming Mouse Pad имеет прорезиненную структуру с особым протектором, что предотвращает скольжение коврика по поверхности стола. Это несомненно, добавляет уверенности в каждом движении.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Razer%20Gigantus%20V2.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "RAZER GOLIATHUS CHROMA MERCURY",
        "brand": "Razer",
        "price": 8900,
        "size": "ОГРОМНЫЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": true,
        "coating": null,
        "material": null,
        "baseMaterial": "РЕЗИНА",
        "dimensions": "920Х294 ММ",
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Игровой коврик Razer Goliathus Chroma Mercury благодаря огромным размерам 92x29.4 см позволит разместить на нем клавиатуру вместе с мышкой. При этом устройства не будут мешать друг другу и вам даже при активной игре. Тканевое покрытие гарантирует точный отклик любой модели мыши и типа сенсора на команды и малейшие движения. Изделие Razer Goliathus Chroma Mercury представлено в серой расцветке, а также дополнено яркой RGB-подсветкой с питанием по облегченному кабелю в оплетке 2.1 м и синхронизацией между устройствами. Это превращает обычный коврик в стильный элемент декора. Аксессуар дополнен балансом контроля и скорости, поддержкой Razer Synapse 3, а также удобным креплением для фиксации шнура компьютерной мыши.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Razer%20Goliathus%20Chroma%20Mercury.png",
        "id": uuid(),
    },
    {
        "type": "Rug",
        "title": "RAZER GIGANTUS V2",
        "brand": "Razer",
        "price": 5200,
        "size": "ОГРОМНЫЙ",
        "color": "ЧЕРНЫЙ",
        "backlight": true,
        "coating": null,
        "material": null,
        "baseMaterial": "РЕЗИНА",
        "dimensions": "940Х410 ММ",
        "wirelesscharger": null,
        "additionalInformation": null,
        "description": "Коврик Razer Gigantus V2 [RZ02-03330400-R3M1] − удобный аксессуар прямоугольной формы, обладающий размерами 940x410x4 мм. Его толщина 4 мм обеспечивает высокую прочность изделия при сохранении комфорта эксплуатации: коврик будет почти не ощутим для пользователя. Верхнее покрытие по технологии speed + control изготавливается из мягкой и эластичной ткани, которая обладает плотной фактурой. Это способствует легкости и высокой скорости скольжения. При этом, точность скольжения сохраняется. Коврик Razer Gigantus V2 [RZ02-03330400-R3M1] ложится на резиновое основание, которое исключает его смещение даже при интенсивных движениях мышью. Пенный наполнитель, размещенный между тканевым и резиновым покрытиями, позволяет коврику оставаться плоским и ровным на любых поверхностях. Аксессуар будет одинаково эффективен для манипуляторов с любой чувствительностью сенсора.",
        "image": "https://lightflightpc.ru/uploads/Devices/Mousepad/Razer%20Gigantus%20V2%201.png",
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Newbie%201/Newbie%201.jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Newbie%201.png",
        "title": "NEWBIE 1",
        "typebuilds": "NEWBIE",
        "price": 54000,
        "description1": "55 FPS на средне-высоких настройках графики",
        "description2": "Для рабочих задач начального уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Хорошее решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 4,
        "ozu": "16 ГБ",
        "videoCart": "GeForce GTX 1650",
        "processor": "Intel Core i3-10100",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Newbie%202/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Newbie%202.jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Newbie%202.png",
        "title": "NEWBIE 2",
        "typebuilds": "NEWBIE",
        "price": 62000,
        "description1": "60 FPS на средне-высоких настройках графики",
        "description2": "Для рабочих задач начального уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Хорошее решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 4,
        "ozu": "16 ГБ",
        "videoCart": "GeForce GTX 1660 super",
        "processor": "Intel Core i3-10100",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Newbie%203/Bez-imeni-1.jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Newbie%203/Newbie%202%20(1).png",
        "title": "NEWBIE 3",
        "typebuilds": "NEWBIE",
        "price": 71000,
        "description1": "60 FPS на средне-высоких настройках графики",
        "description2": "Для рабочих задач начального уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Хорошее решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 4,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 3050 Dual",
        "processor": "Intel Core i3-10100",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Newbie%204/Newbie%204%20(1).jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Newbie%204%20(2).png",
        "title": "NEWBIE 4",
        "typebuilds": "NEWBIE",
        "price": 75800,
        "description1": "60 FPS на средне-высоких настройках графики",
        "description2": "Для рабочих задач начального уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Хорошее решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 4,
        "ozu": "16 ГБ",
        "videoCart": "AMD Radeon RX 6600 Fighter",
        "processor": "Intel Core i3-12100",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Standard%201/Standard%201.jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Standard%201/Standard%201%20(main).png",
        "title": "STANDARD 1",
        "typebuilds": "STANDART",
        "price": 82000,
        "description1": "60 FPS на высоких настройках графики",
        "description2": "Для рабочих задач среднего уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 6,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 2060 OC",
        "processor": "Intel Core i5-10400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Standart%202/Standart%202.jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Standart%202/Standart_2-removebg-preview.png",
        "title": "STANDARD 2",
        "typebuilds": "STANDART",
        "price": 87000,
        "description1": "65 FPS на высоких настройках графики",
        "description2": "Для рабочих задач среднего уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 6,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 3060 GAMING",
        "processor": "Intel Core i5-10400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Standard%203/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Standard%203%20(1).jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Standard%203/Standard%203%20(Main).png",
        "title": "STANDARD 3",
        "typebuilds": "STANDART",
        "price": 88000,
        "description1": "75 FPS на высоких настройках графики",
        "description2": "Для рабочих задач среднего уровня",
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 6,
        "ozu": "16 ГБ",
        "videoCart": "AMD Radeon RX 6650 XT",
        "processor": "Intel Core i5-10400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Standard%204/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Standard%204%20(1).jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Standard%204/Standard%204%20(main).png",
        "title": "STANDARD 4",
        "typebuilds": "STANDART",
        "price": 90000,
        "description1": "85 FPS на ультра-высоких настройках графики",
        "description2": "Для рабочих задач среднего уровня", 
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 6,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 3060",
        "processor": "Intel Core i5-10400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Pro%201/Pro%201%20(1).jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Pro%201/Pro%201%20(main).png",
        "title": "PRO 1",
        "typebuilds": "PRO",
        "price": 98000,
        "description1": "78 FPS на ультра настройках графики",
        "description2": "Для рабочих задач высокого уровня", 
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 6,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 3060",
        "processor": "Intel Core i5-12400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Pro%202/Pro%202%20(1).jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Pro%202/Pro%202.png",
        "title": "PRO 2",
        "typebuilds": "PRO",
        "price": 110000,
        "description1": "75 FPS на ультра настройках графики",
        "description2": "Для рабочих задач среднего уровня", 
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 6,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 3060 Ti",
        "processor": "Intel Core i5-12400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Pro%205/%D0%9D%D0%B0%D1%88%D0%B8%20%D1%84%D0%BE%D1%82%D0%BE/Bez-imeni-1%20(1).jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Pro%205.png",
        "title": "PRO 3",
        "typebuilds": "PRO",
        "price": 121000,
        "description1": "100 FPS на ультра настройках графики",
        "description2": "Для рабочих задач высокого уровня", 
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 6,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 3070",
        "processor": "Intel Core i5-12400",
        "interface": false,
        "id": uuid(),
    },
    {
        "type": "Readybuild",
        "image": "https://lightflightpc.ru/uploads/PC/Pro%204/Pro%204.jpg",
        "windowimage": "https://lightflightpc.ru/uploads/PC/Pro%204/Pro%204%20(main).png",
        "title": "PRO 4",
        "typebuilds": "PRO",
        "price": 140000,
        "description1": "115 FPS на ультра настройках графики",
        "description2": "Для рабочих задач высокого уровня", 
        "description3": "Гарантийное обслуживание в течение года",
        "description4": "Отличное решение для игр",
        "description5": "Установка Windows 10 и необходимых драйверов",
        "description6": "6-ти часовое стресс-тестирование",
        "nuclei": 10,
        "ozu": "16 ГБ",
        "videoCart": "GeForce RTX 3070",
        "processor": "Intel Core i5-13400",
        "interface": false,
        "id": uuid(),
    },
]